[tool.poetry]
name = "t3"
version = "0.1.0"
description = "Run Python Script and Tests"
authors = ["Amanda Wood"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
